### PR TITLE
Fix `stringify()` in net and host to respect host

### LINKED ISSUE #47: Stringify may be returning the wrong address for net and ws
See: https://github.com/ssbc/patchwork/issues/1035

We have a scenario where `config.connections.incoming` is specifying the correct IP addresses but it looks like this code is still falling back to multiserver-scopes (i.e. non-private-ip) in the local scope: https://github.com/ssbc/multiserver/blob/1fefc75e2423e00270f5f0d46fec3b485776d7fb/plugins/net.js#L92

I'd imagine that this is a bug *or* maybe I'm completely misunderstanding what this is supposed to do? For example, my config:

```javascript
{ net:
  [ { host: '127.0.0.1',
    port: 8008,
    scope: [ 'device' ],
    transform: 'shs' },
    { host: '::1', port: 8008, scope: [ 'device' ], transform: 'shs' },
    { host: '192.168.0.109',
      port: 8008,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' },
    { host: '172.18.0.1',
      port: 8008,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' },
    { host: 'fce2:9811:4862:81a7:bb08:91d6:2e41:d220',
      port: 8008,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' } ],
  ws:
  [ { host: '127.0.0.1',
    port: 8989,
    scope: [ 'device' ],
    transform: 'shs' },
    { host: '::1', port: 8989, scope: [ 'device' ], transform: 'shs' },
    { host: '192.168.0.109',
      port: 8989,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' },
    { host: '172.18.0.1',
      port: 8989,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' },
    { host: 'fce2:9811:4862:81a7:bb08:91d6:2e41:d220',
      port: 8989,
      scope: [ 'device', 'local', 'public' ],
      transform: 'shs' } ],
  unix: [ { scope: 'device', transform: 'noauth' } ] } }

```

But over the network I see:

```
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=;ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

Replacing the semicolons with newlines (I'd love if this was the default):

```
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

Maybe relevant: https://github.com/ssbc/multiserver/issues/22

cc: @dominictarr @arj03 @regular @cryptix

### PR DESCRIPTION
**Pull request by christianbundy**
Previously we were disregarding the `host` setting for all configs
except in cases where `scope === 'public' && `opts.external != null`.
This resolves the error by first checking whether `opts.host` is defined
before falling back to automatic detection methods.

---

Resolves #47 

## Before

```
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

## After

```
net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:172.18.0.1:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:fce2:9811:4862:81a7:bb08:91d6:2e41:d220:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.0.109:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://172.18.0.1:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://[fce2:9811:4862:81a7:bb08:91d6:2e41:d220]:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

cc: @dominictarr @arj03 @regular @cryptix @the-kenny

### CODE REVIEW

**Comment by arj03** [comment]
The code is a bit confusing, like host is defined [here](https://github.com/ssbc/multiserver/blob/1fefc75e2423e00270f5f0d46fec3b485776d7fb/plugins/net.js#L25) but is only used in the server code it seems. Also stringify has a close but different interpretation of host.

Would be nice with some tests of this stuff. There are so many configurations to take into account.

**Comment by arj03** [comment]
A bit more context for other people reading this. Seems to be this [commit](https://github.com/ssbc/multiserver/commit/f064349235fffed36adcc762adc2f6eb1dee9344) where multiserver scopes is always picking the default for the scope. So this is only a problem if you have multiple interfaces.

**Comment by christianbundy** [comment]
Yeah, I think I've cleaned it up about as well as I'm able to without making any breaking changes, but it's still a bit hairy. Hopefully the comments are useful for future code spelunkers and the bugfix is useful for folks with multiple network interfaces (apparently common on macOS (see https://github.com/ssbc/patchwork/issues/1035)).

File: plugins/ws.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ module.exports = function (opts) {
       else
         port = opts.port
 
-      var host = (scope == 'public' && opts.external) || scopes.host(scope)
+      var host = opts.host || (scope == 'public' && opts.external) || scopes.host(scope)
```
Comment (arj03) [inline plugins/ws.js]: Shouldn't this also be public, then host, then scopes?

**Comment by arj03** [comment]
Nice refactor @christianbundy. Still thinking about writing a test, maybe I can have a go at that.

**Comment by arj03** [comment]
Pushed up two tests

**Comment by the-kenny** [comment]
Hey there! I'm the guy who originally discovered the issue on my machines.

I just rebuilt `Patchwork` using the latest `multiserver` from this branch (`package-lock.json` shows commit e9376b575f38e7fb1ffa676ca2e64ef3bf42f547 and I can report there is at least some progress :-)

Right now `sudo tcpdump -s 0 -u port 8008 -A` (plus some formatting) displays the following announcement:

```
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://10.10.20.73:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://[2a0a:a545:2448:0:189a:8e5d:ef83:8eff]:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://[2a0a:a545:2448:0:e1a4:d7c8:5d23:5d54]:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://192.168.92.45:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
```

So there's definitely progress for the `ws://` side of things. However, the `net:` announcements are still using the IP of a single (disconnected) interface.

related to https://github.com/ssbc/patchwork/issues/1035

**Comment by the-kenny** [comment]
Hey there! I'm the guy who originally discovered the issue on my machines.

I just rebuilt Patchwork using the latest multiserver from this branch (`package-lock.json` shows commit e9376b5 and I can report there is at least some progress :-)

Right now `tcpdump -s 0 -u port 8008 -A` (plus some formatting) displays the following announcement:

```
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
net:fe80::aede:48ff:fe00:1122:8008~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://10.10.20.73:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://[2a0a:a545:2448:0:189a:8e5d:ef83:8eff]:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
ws://[2a0a:a545:2448:0:e1a4:d7c8:5d23:5d54]:8989~shs:mucTrTjExFklGdAFobgY4zypBAZMVi7q0m6Ya55gLVo=
```

So there's definitely progress for the `ws://` side of things. However, the `net:` announcements are still using the IP of a single (disconnected) interface.

related to ssbc/patchwork#1035

File: plugins/ws.js (hunk 1 above)
Comment (christianbundy) [reply plugins/ws.js]: Yep, great catch.

**Comment by christianbundy** [comment]
@the-kenny 

Hey, could you run `npm ls multiserver` and ensure that it looks like this:

```console
$ npm ls multiserver
ssb-patchwork@3.12.0-beta.2 /home/christianbundy/src/ssbc/patchwork
├─┬ ssb-client@4.7.4
│ └── UNMET DEPENDENCY multiserver@3.3.2 
├─┬ ssb-server@14.1.12 (github:ssbc/ssb-server#982a053a608a19de59638c0056832bce34b8436b)
│ ├── UNMET DEPENDENCY multiserver@3.3.2 
│ ├─┬ secret-stack@6.1.2
│ │ └── UNMET DEPENDENCY multiserver@3.3.2 
│ └─┬ ssb-ws@5.1.1
│   └── UNMET DEPENDENCY multiserver@3.3.2 
└─┬ ssb-ws@6.0.0
  └── UNMET DEPENDENCY multiserver@3.3.2 

npm ERR! missing: multiserver@3.3.2, required by ssb-client@4.7.4
npm ERR! missing: multiserver@3.3.2, required by ssb-server@14.1.12
npm ERR! missing: multiserver@3.3.2, required by secret-stack@6.1.2
npm ERR! missing: multiserver@3.3.2, required by ssb-ws@5.1.1
npm ERR! missing: multiserver@3.3.2, required by ssb-ws@6.0.0
```

Unfortunately ssb-server has a shrinkwrap file, which means that a normal `npm link` doesn't affect those dependencies. If you're using `npm install` to test this commit it won't get those dependencies either, which makes it hard. I can confirm that on this branch I'm still seeing the fixed values:

```
net:192.168.3.55:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:172.18.0.1:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
net:fce2:9811:4862:81a7:bb08:91d6:2e41:d220:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://192.168.3.55:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://172.18.0.1:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
ws://[fce2:9811:4862:81a7:bb08:91d6:2e41:d220]:8989~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=
```

I don't think there's an easy way to test this in Patchwork right now.

**Comment by christianbundy** [comment]
Also: thanks a bunch for adding those tests!

**Comment by the-kenny** [comment]
@christianbundy sure, here you are!

```
$ npm ls multiserver
ssb-patchwork@3.12.0-beta.2 /Users/moritz/dev/patchwork
├── multiserver@3.3.2  (github:ssbc/multiserver#a6285b2282ca3d3ce78a6b47ced28324d64e4b3f)
├─┬ ssb-client@4.7.5
│ └── multiserver@3.3.2  deduped (github:ssbc/multiserver#a6285b2282ca3d3ce78a6b47ced28324d64e4b3f)
├─┬ ssb-server@14.1.12
│ ├── multiserver@3.3.2
│ ├─┬ secret-stack@6.1.0
│ │ └── multiserver@3.3.2  deduped
│ ├─┬ ssb-client@4.7.2
│ │ └── multiserver@3.3.2  deduped
│ └─┬ ssb-ws@5.1.1
│   └── multiserver@3.3.2  deduped
└─┬ ssb-ws@6.0.0
  └── multiserver@3.3.2  deduped (github:ssbc/multiserver#a6285b2282ca3d3ce78a6b47ced28324d64e4b3f)
```

Note that I added `multiserver` as a dependency pointing to this branch directly to `patchwork` to override whatever version its dependencies use.

**Comment by arj03** [comment]
@the-kenny looks as if the depedency in ssb-server is still pointing to 3.3.2 and not this branch, that is probably why its not working is my guess.

**Comment by the-kenny** [comment]
@arj03 Oh, are you sure? I thought the git-ref to the latest commit in this branch and all the `deduped` markers tell me it's using the correct one.

**Comment by christianbundy** [comment]
That's my understanding as well. The ssb-server shrinkwrap makes it so that you can't easily change versions. You can confirm with `find node_modules -name multiserver` I think, that should output all of the different instances of the multiserver dependency.

Maybe you can delete the `ssb-server/node_modules/multiserver` and replace it with the one from Git? No easy way to do this with mom though.

**Comment by the-kenny** [comment]
@christianbundy Wow, NPM really is a mess. The hack to replace `ssb-server/node_modules/multiserver` did it. I'm annoucing the correct IPs not :-) Thanks for taking your time with this.

**Comment by christianbundy** [comment]
:fearful: Shrinkwraps... :scream:

**Comment by arj03** [comment]
@christianbundy everyone is at dtn, so don't expect much reply to this for a few days, but for me this looks ready to merge.

**Comment by christianbundy** [comment]
Oh, I'd totally forgotten about that. I'll merge and release as a patch, then I'll push my *other* multiserver branch. :upside_down_face:
